"""Stable domain contracts used by the application and presentation layers."""

from .hud import (
    HudConnectionStatus,
    HudEvent,
    HudEventListener,
    HudLoginFailed,
    HudMessageReceived,
    HudOperation,
    HudOperationFailed,
    HudSendResult,
    HudState,
    HudStateChanged,
)
from .messages import (
    DanmakuMessage,
    GiftCurrency,
    GiftMessage,
    HudMessage,
    ImageSegment,
    InteractionKind,
    InteractMessage,
    MessageAuthor,
    MessageBadge,
    MessageBadgeKind,
    MessageSegment,
    ReplySegment,
    SystemMessage,
    SystemMessageLevel,
    TextSegment,
    make_system_message,
)

__all__ = (
    "DanmakuMessage",
    "GiftMessage",
    "GiftCurrency",
    "HudMessage",
    "HudConnectionStatus",
    "HudEvent",
    "HudEventListener",
    "HudLoginFailed",
    "HudMessageReceived",
    "HudOperation",
    "HudOperationFailed",
    "HudSendResult",
    "HudState",
    "HudStateChanged",
    "ImageSegment",
    "InteractionKind",
    "InteractMessage",
    "MessageAuthor",
    "MessageBadge",
    "MessageBadgeKind",
    "MessageSegment",
    "ReplySegment",
    "SystemMessage",
    "SystemMessageLevel",
    "TextSegment",
    "make_system_message",
)
