"""Application coordination for Mirror settings, lifecycle, and message publication."""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, replace

from ..config.store import AppConfig, ConfigStore
from ..danmaku.messages import HudMessage, SystemMessageLevel
from ..mirror.state import MIRROR_DEFAULT_PORT, MIRROR_ROUTE, MirrorEntry, MirrorState
from .mirror_server import MirrorServer, MirrorServerFactory


@dataclass(frozen=True, slots=True)
class MirrorCoordinatorState:
    """Immutable presentation state for the local Mirror workflow."""

    enabled: bool
    running: bool
    port: int
    url: str
    error: str = ""

    @property
    def status_text(self) -> str:
        """Return the localized status shown by the settings dialog."""
        if self.running:
            return "已启动"
        if self.error:
            return f"启动失败: {self.error}"
        if self.enabled:
            return "已启用，当前未启动"
        return "未启动"


@dataclass(frozen=True, slots=True)
class MirrorNotice:
    """Describe one user-visible result generated by a Mirror operation."""

    text: str
    level: SystemMessageLevel = SystemMessageLevel.INFO


@dataclass(frozen=True, slots=True)
class MirrorOperationResult:
    """Return the latest state and notices from one asynchronous operation."""

    state: MirrorCoordinatorState
    notices: tuple[MirrorNotice, ...] = ()


class MirrorCoordinator:
    """Own Mirror configuration, serialized message history, and server lifecycle."""

    def __init__(
        self,
        *,
        config_store: ConfigStore,
        server_factory: MirrorServerFactory,
    ) -> None:
        """Create a coordinator with explicit persistence and HTTP capabilities."""
        self._config_store: ConfigStore = config_store
        self._server_factory: MirrorServerFactory = server_factory
        self._message_state: MirrorState = MirrorState()
        self._state: MirrorCoordinatorState = self._make_state(enabled=False, port=MIRROR_DEFAULT_PORT)
        self._server: MirrorServer | None = None
        self._operation_lock: asyncio.Lock = asyncio.Lock()
        self._shutting_down: bool = False
        self._shutdown_complete: bool = False

    @property
    def state(self) -> MirrorCoordinatorState:
        """Return the immutable state snapshot used by presentation code."""
        return self._state

    @property
    def message_state(self) -> MirrorState:
        """Return the bounded message history owned by this coordinator."""
        return self._message_state

    def load_settings(self) -> MirrorCoordinatorState:
        """Load Mirror settings through the configuration boundary."""
        self.apply_config(self._config_store.load())
        return self._state

    def apply_config(self, config: AppConfig) -> None:
        """Apply startup settings before the coordinator begins serving clients."""
        if self._server is not None:
            raise RuntimeError("Mirror 已启动，不能重新加载设置")
        if self._shutting_down or self._shutdown_complete:
            raise RuntimeError("Mirror 协调器已关闭")
        self._state = self._make_state(enabled=config.mirror_enabled, port=config.mirror_port)

    async def start(self) -> MirrorOperationResult:
        """Start the configured Mirror server and report bind failures as state."""
        async with self._operation_lock:
            self._ensure_open()
            if not self._state.enabled:
                return self._result()
            return await self._start_locked()

    async def stop(self) -> MirrorOperationResult:
        """Stop the server while preserving the user's enabled startup preference."""
        async with self._operation_lock:
            self._ensure_open()
            return await self._stop_locked()

    async def set_enabled(self, enabled: bool) -> MirrorOperationResult:
        """Persist the enabled preference and start or stop the local server."""
        async with self._operation_lock:
            self._ensure_open()
            notices = list(self._save_enabled(enabled))
            self._state = replace(self._state, enabled=enabled, error="")
            if enabled:
                result = await self._start_locked()
            else:
                result = await self._stop_locked()
                notices.append(MirrorNotice("BiliHUD Mirror 已停止。"))
            return replace(result, notices=tuple((*notices, *result.notices)))

    async def shutdown(self) -> MirrorOperationResult:
        """Stop the server permanently and make repeated shutdown calls harmless."""
        async with self._operation_lock:
            if self._shutdown_complete:
                return self._result()
            self._shutting_down = True
            result = await self._stop_locked()
            self._shutdown_complete = True
            return result

    def publish_message(self, message: HudMessage) -> MirrorEntry:
        """Serialize and retain a normalized message, then publish it when serving."""
        entry = self._message_state.add_message(message)
        server = self._server
        if server is not None:
            server.publish_append(entry)
        return entry

    async def _start_locked(self) -> MirrorOperationResult:
        """Start the server while the operation lock is held."""
        server = self._server
        if server is not None:
            self._state = replace(self._state, running=True, url=server.url, error="")
            return self._result()

        try:
            server = self._server_factory(self._message_state, port=self._state.port)
            await server.start()
        except OSError as exc:
            self._state = replace(self._state, running=False, error=str(exc))
            return self._result(
                MirrorNotice(
                    f"BiliHUD Mirror 启动失败: {exc}",
                    SystemMessageLevel.ERROR,
                )
            )

        self._server = server
        self._state = replace(self._state, running=True, url=server.url, error="")
        return self._result(MirrorNotice(f"BiliHUD Mirror 已启动: {server.url}"))

    async def _stop_locked(self) -> MirrorOperationResult:
        """Stop the current server without losing its reference on cleanup failure."""
        server = self._server
        if server is None:
            self._state = replace(
                self._state,
                running=False,
                url=self._url_for_port(self._state.port),
            )
            return self._result()

        try:
            await server.stop()
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            self._state = replace(self._state, running=True, error=str(exc))
            raise

        self._server = None
        self._state = replace(
            self._state,
            running=False,
            url=self._url_for_port(self._state.port),
            error="",
        )
        return self._result()

    def _save_enabled(self, enabled: bool) -> tuple[MirrorNotice, ...]:
        """Persist only Mirror fields while retaining unrelated application settings."""
        current = self._config_store.load()
        updated = replace(current, mirror_enabled=enabled, mirror_port=self._state.port)
        if self._config_store.save(updated):
            return ()
        return (MirrorNotice("BiliHUD Mirror 设置保存失败。", SystemMessageLevel.ERROR),)

    def _ensure_open(self) -> None:
        """Reject new operations once shutdown has started."""
        if self._shutting_down or self._shutdown_complete:
            raise RuntimeError("Mirror 协调器已关闭")

    def _result(self, *notices: MirrorNotice) -> MirrorOperationResult:
        """Build an operation result from the current coordinator state."""
        return MirrorOperationResult(self._state, notices)

    @classmethod
    def _make_state(cls, *, enabled: bool, port: int, error: str = "") -> MirrorCoordinatorState:
        """Build a normalized state with the stable local Mirror endpoint."""
        return MirrorCoordinatorState(
            enabled=enabled,
            running=False,
            port=port,
            url=cls._url_for_port(port),
            error=error,
        )

    @staticmethod
    def _url_for_port(port: int) -> str:
        """Return the local browser endpoint used before a server is running."""
        return f"http://127.0.0.1:{port}{MIRROR_ROUTE}"


__all__ = (
    "MirrorCoordinator",
    "MirrorCoordinatorState",
    "MirrorNotice",
    "MirrorOperationResult",
)
